{% set version = '2018.2.0' %}
{% set qiime2release = '2017.12' %}

package:
  name: q2-fragment-insertion
  version: {{ version }}

source:
  - git_url: https://github.com/biocore/q2-fragment-insertion.git
  #~ git_rev: {{ version }}  # use a tagged version once the recipe is merged into master and a tag has been created
  - path: ../../taxonomy_gg99.qza
  - path: ../../silva12.8.taxonomy.qza

build:
  number: 1
  script:
    - cp taxonomy_gg99.qza $PREFIX/share/fragment-insertion/ref/
    - cp silva12.8.taxonomy.qza $PREFIX/share/fragment-insertion/ref/
    - python setup.py install
    - mkdir -p $PREFIX/share/q2-fragment-insertion/ref/
    # Silva 12.8 reference files are provided with "fragment-insetion" conda package and are here imported into qiime2 archived for convenience of end users
    - qiime tools import --type "Phylogeny[Rooted]" --input-path $PREFIX/share/fragment-insertion/ref/silva12.8_99otus_aligned_masked1977.tre --output-path $PREFIX/share/q2-fragment-insertion/ref/silva12.8.tree.qza
    - qiime tools import --type "FeatureData[AlignedSequence]" --input-path $PREFIX/share/fragment-insertion/ref/silva12.8_99otus_aligned_masked1977.fasta --output-path $PREFIX/share/q2-fragment-insertion/ref/silva12.8.alignment.qza
    - qiime tools import --type "RAxMLinfo" --input-path $PREFIX/share/fragment-insertion/ref/silva12.8_99otus_aligned_masked1977.info --output-path $PREFIX/share/q2-fragment-insertion/ref/silva12.8.raxmlinfo.qza

requirements:
  build:
    - python 3.5*
    - setuptools
    - nodejs
    - fragment-insertion
    - biom-format >=2.1.5,<2.2.0
    - qiime2 >={{ qiime2release }}.*
    - q2templates >={{ qiime2release }}.*
    - q2-types >={{ qiime2release }}.*
    - q2-feature-table >={{ qiime2release }}.*
    - q2cli >={{ qiime2release }}.*

  run:
    - python 3.5*
    - setuptools
    - nodejs
    - fragment-insertion
    - biom-format >=2.1.5,<2.2.0
    - qiime2 >={{ qiime2release }}.*
    - q2templates >={{ qiime2release }}.*
    - q2-types >={{ qiime2release }}.*
    - q2-feature-table >={{ qiime2release }}.*
    - q2cli >={{ qiime2release }}.*
    - q2-types >={{ qiime2release }}.*

test:
  source_files:
    - q2_fragment_insertion/tests/data/reference_alignment_tiny.qza
    - q2_fragment_insertion/tests/data/reference_phylogeny_tiny.qza
    - q2_fragment_insertion/tests/data/real_data.qza
  commands:
    - qiime fragment-insertion sepp --i-representative-sequences q2_fragment_insertion/tests/data/real_data.qza --i-reference-alignment q2_fragment_insertion/tests/data/reference_alignment_tiny.qza --i-reference-phylogeny q2_fragment_insertion/tests/data/reference_phylogeny_tiny.qza --output-dir ./test_conda_tmp/
    - qiime tools export --output-dir ./test_conda_tmp/ ./test_conda_tmp/tree.qza
    - ls test_conda_tmp/tree.nwk
  imports:
    - q2_fragment_insertion

about:
  home: https://github.com/biocore/q2-fragment-insertion
  license: BSD-3-Clause
  license_family: BSD
